---
-
  name: Disable 'root' SSH Access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{  item.regexp }}"
    line: "{{  item.line }}"
    state: present
#  notify: restart sshd
  with_items:
    - { regexp: "^#PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^#PasswordAuthentication", line: "PasswordAuthentication no" }
### The following line is braking CentOS  ###  Seems to be working with Debian based.
    - { regexp: "^#GSSAPIAuthentication", line: "GSSAPIAuthentication no" }
