---
-
  name: Install Fail2ban "Debian"
  package: name=fail2ban state=present
  when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"
-
# Extra Packages for Enterprise Linux
  name: Install EPEL 'CentOS' 
  package: name=epel-release state=present
  when: "ansible_distribution == \"CentOS\""
-
# needed for previus play to catchup
  name: Pause 'CentOS'
  wait_for:
    timeout: 2
  when: "ansible_distribution == \"CentOS\""
-
  name: Install Fail2ban "CentOS"
  package: name=fail2ban state=present
  when: "ansible_distribution == \"CentOS\""
#-
#  name: Configure Fail2ban
#  lineinfile:
#    dest: /etc/fail2ban
#    regexp: '^'
-
  name: Start Fail2ban
  service:
    name: fail2ban
    enabled: yes
    state: restarted
