---
-
  name: Add 'admin' Group
  group: name=admin state=present
-
  name: Add 'admin group' to Sudoers file
  tags: always
  lineinfile: 
    dest: /etc/sudoers
    regexp: '^%ADMIN ALL\='
    line: 'ADMIN ALL=(ALL) NOPASSWD:ALL'
    state: present
    validate: 'visudo -cf %s'  
-
  name: Add admin user - 'colin'
  tags: always
  user:
    name: colin
#    password: {{ user_pass }}
    shell: /bin/bash
    groups: admin
    append: yes
-
  name: Add 'colin' ssh pub key
  tags: always
  authorized_key:
    user: colin
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEjy3RxyTuH7vB+AElYkEZdzr9JwoE4uQgOdLrp5xSwR # cTesting-Key = colin Testin_FarmNet.lab Key"
    state: present
-
  name: Add 'colin' Sudoers File
  tags: always
  copy:
    src: files/colin
    dest: /etc/sudoers.d/colin
    owner: root
    group: root
    mode: 0440