---
-
  name: Create Ansible user HAL
  become: true
  tags: always
  user:
    name: HAL_ansible
    group: sudo
  when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"
-
  name: CentOS 'Wheel' user
  become: true
  tags: always
  user:
    name: HAL_ansible
    group: wheel
  when: ansible_distribution == "CentOS"
-
  name: Add HAL ssh key
  become: true
  tags: always
  authorized_key:
    user: HAL_ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFPbHqTPxqkKIVO0cYDSM5esooxmfNr6ECa1k5YxGJ4D HAL_ansible FarmNet.Lab Key"
-
  name: Add HAL Sudoers File
  become: true
  tags: always
  copy:
    src: files/sudoers_HAL
    dest: /etc/sudoers.d/HAL_ansible
    owner: root
    group: root
    mode: 0440